### ISSUE TITLE
thanos photos are not there..😡😡

### ISSUE THREAD

**Issue by psriramnaidu** [varaprasadh/free-pics#11]
we are very sad to see this repo without his pics. kindly upload them otherwise we will destroy you.

**Comment by varaprasadh** [comment]
yup,our universe is already dead, we dont need him right now.

**Comment by psriramnaidu** [comment]
take the help of tony recreate ur universe and send pics of thanos :>)

**Comment by varaprasadh** [comment]
get the hell out of here

**Comment by psriramnaidu** [comment]
So u don't like ur family

**Comment by varaprasadh** [comment]
well, we will try to handle thanos, tony and hulk making their best

**Comment by psriramnaidu** [comment]
ok goodluck dude, c u after war!!!

**Comment by psriramnaidu** [comment]
tg

**Comment by varaprasadh** [comment]
war has ended dude, thanos dead we got him.

**Comment by psriramnaidu** [comment]
congrats dude! send pics of thanos for cermony
